<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>HeThongDoKhoangCach</RootNamespace>
    <AssemblyName>HeThongDoKhoangCach</AssemblyName>
    <Version>1.0.0</Version>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Data\master.csv" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
